### ISSUE TITLE
Continue + Break

### ISSUE THREAD

**Issue by serwansj** [bendisposto/propra_book#12]

**Comment by badBlackShark** [comment]
Ich hab gerade mal drüber geguckt. Sieht gut aus.

**Comment by Grimaldus12** [comment]
Ich habe es auch mal durchgelesen und finde es sehr gut. Eventuell kannst du noch whtiespaces in den Code-Beispielen zwischen den Keywords und dem Statement (if (statement) anstatt if(statement)) machen, dann ist der Code auch schon nach Sun Standards formatiert
