### ISSUE TITLE
Klassen und Objekte

### ISSUE THREAD

**Issue by mipot101** [bendisposto/propra_book#8]

**Comment by brokelyn** [comment]
Ich habe mal eine grobe Verbesserung hochgeladen. Auf den Inhalt habe ich nicht den Fokus gelegt.

**Comment by Grimaldus12** [comment]
Ich finde das soweit sehr gut formuliert und auch gut durch die Beispiele untermauert. Vielleicht sollte man bei der Tabelle zu den Zugriffsrechten in einem Satz danach nochmal erklären was genau das besondere an der Relation "Unterklasse" ist, da Verebung bis zu diesem Punkt im Dokument noch nicht erklärt wurde. Ansonsten würde ich das so unterschreiben.

**Comment by mipot101** [comment]
Ja, das stimmt. Ich hab einen entsprechenden Verweis eingefügt.
